# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gRPC.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngRPC.proto\x12\x0buserservice\"J\n\x0bUserMessage\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\"\x13\n\x11\x43reateUserRequest\"\x14\n\x12\x43reateUserResponse\".\n\x0eGetUserRequest\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c\"/\n\x0fGetUserResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c\"\x13\n\x11UpdateUserRequest\"\x14\n\x12UpdateUserResponse\"\x13\n\x11\x44\x65leteUserRequest\"\x14\n\x12\x44\x65leteUserResponse2\xc0\x02\n\x0bUserService\x12M\n\nCreateUser\x12\x1e.userservice.CreateUserRequest\x1a\x1f.userservice.CreateUserResponse\x12\x44\n\x07GetUser\x12\x1b.userservice.GetUserRequest\x1a\x1c.userservice.GetUserResponse\x12M\n\nUpdateUser\x12\x1e.userservice.UpdateUserRequest\x1a\x1f.userservice.UpdateUserResponse\x12M\n\nDeleteUser\x12\x1e.userservice.DeleteUserRequest\x1a\x1f.userservice.DeleteUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gRPC_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERMESSAGE']._serialized_start=27
  _globals['_USERMESSAGE']._serialized_end=101
  _globals['_CREATEUSERREQUEST']._serialized_start=103
  _globals['_CREATEUSERREQUEST']._serialized_end=122
  _globals['_CREATEUSERRESPONSE']._serialized_start=124
  _globals['_CREATEUSERRESPONSE']._serialized_end=144
  _globals['_GETUSERREQUEST']._serialized_start=146
  _globals['_GETUSERREQUEST']._serialized_end=192
  _globals['_GETUSERRESPONSE']._serialized_start=194
  _globals['_GETUSERRESPONSE']._serialized_end=241
  _globals['_UPDATEUSERREQUEST']._serialized_start=243
  _globals['_UPDATEUSERREQUEST']._serialized_end=262
  _globals['_UPDATEUSERRESPONSE']._serialized_start=264
  _globals['_UPDATEUSERRESPONSE']._serialized_end=284
  _globals['_DELETEUSERREQUEST']._serialized_start=286
  _globals['_DELETEUSERREQUEST']._serialized_end=305
  _globals['_DELETEUSERRESPONSE']._serialized_start=307
  _globals['_DELETEUSERRESPONSE']._serialized_end=327
  _globals['_USERSERVICE']._serialized_start=330
  _globals['_USERSERVICE']._serialized_end=650
# @@protoc_insertion_point(module_scope)
