# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protobufs.CrisisDeck_pb2 as CrisisDeck__pb2


class ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/Service/CreateUser',
                request_serializer=CrisisDeck__pb2.User.SerializeToString,
                response_deserializer=CrisisDeck__pb2.User.FromString,
                )
        self.GetUser = channel.unary_unary(
                '/Service/GetUser',
                request_serializer=CrisisDeck__pb2.User.SerializeToString,
                response_deserializer=CrisisDeck__pb2.User.FromString,
                )
        self.UpdateUser = channel.unary_unary(
                '/Service/UpdateUser',
                request_serializer=CrisisDeck__pb2.User.SerializeToString,
                response_deserializer=CrisisDeck__pb2.User.FromString,
                )
        self.DeleteUser = channel.unary_unary(
                '/Service/DeleteUser',
                request_serializer=CrisisDeck__pb2.UserID.SerializeToString,
                response_deserializer=CrisisDeck__pb2.Empty.FromString,
                )
        self.CreateEvent = channel.unary_unary(
                '/Service/CreateEvent',
                request_serializer=CrisisDeck__pb2.Event.SerializeToString,
                response_deserializer=CrisisDeck__pb2.Event.FromString,
                )
        self.GetEvent = channel.unary_unary(
                '/Service/GetEvent',
                request_serializer=CrisisDeck__pb2.EventID.SerializeToString,
                response_deserializer=CrisisDeck__pb2.Event.FromString,
                )
        self.UpdateEvent = channel.unary_unary(
                '/Service/UpdateEvent',
                request_serializer=CrisisDeck__pb2.Event.SerializeToString,
                response_deserializer=CrisisDeck__pb2.Event.FromString,
                )
        self.DeleteEvent = channel.unary_unary(
                '/Service/DeleteEvent',
                request_serializer=CrisisDeck__pb2.EventID.SerializeToString,
                response_deserializer=CrisisDeck__pb2.Empty.FromString,
                )
        self.GetEventByUser = channel.unary_stream(
                '/Service/GetEventByUser',
                request_serializer=CrisisDeck__pb2.UserID.SerializeToString,
                response_deserializer=CrisisDeck__pb2.Event.FromString,
                )
        self.CreateQuery = channel.unary_unary(
                '/Service/CreateQuery',
                request_serializer=CrisisDeck__pb2.Query.SerializeToString,
                response_deserializer=CrisisDeck__pb2.Query.FromString,
                )
        self.GetQuery = channel.unary_unary(
                '/Service/GetQuery',
                request_serializer=CrisisDeck__pb2.QueryID.SerializeToString,
                response_deserializer=CrisisDeck__pb2.Query.FromString,
                )
        self.UpdateQuery = channel.unary_unary(
                '/Service/UpdateQuery',
                request_serializer=CrisisDeck__pb2.Query.SerializeToString,
                response_deserializer=CrisisDeck__pb2.Query.FromString,
                )
        self.DeleteQuery = channel.unary_unary(
                '/Service/DeleteQuery',
                request_serializer=CrisisDeck__pb2.QueryID.SerializeToString,
                response_deserializer=CrisisDeck__pb2.Empty.FromString,
                )
        self.CreateTweet = channel.unary_unary(
                '/Service/CreateTweet',
                request_serializer=CrisisDeck__pb2.Tweet.SerializeToString,
                response_deserializer=CrisisDeck__pb2.Tweet.FromString,
                )
        self.GetTweet = channel.unary_unary(
                '/Service/GetTweet',
                request_serializer=CrisisDeck__pb2.TweetID.SerializeToString,
                response_deserializer=CrisisDeck__pb2.Tweet.FromString,
                )
        self.UpdateTweet = channel.unary_unary(
                '/Service/UpdateTweet',
                request_serializer=CrisisDeck__pb2.Tweet.SerializeToString,
                response_deserializer=CrisisDeck__pb2.Tweet.FromString,
                )
        self.DeleteTweet = channel.unary_unary(
                '/Service/DeleteTweet',
                request_serializer=CrisisDeck__pb2.TweetID.SerializeToString,
                response_deserializer=CrisisDeck__pb2.Empty.FromString,
                )
        self.SearchTweet = channel.unary_stream(
                '/Service/SearchTweet',
                request_serializer=CrisisDeck__pb2.Filters.SerializeToString,
                response_deserializer=CrisisDeck__pb2.Tweet.FromString,
                )
        self.GetTweetsByEvent = channel.unary_stream(
                '/Service/GetTweetsByEvent',
                request_serializer=CrisisDeck__pb2.TweetID.SerializeToString,
                response_deserializer=CrisisDeck__pb2.Tweet.FromString,
                )


class ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTweet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTweet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTweet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTweet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchTweet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTweetsByEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=CrisisDeck__pb2.User.FromString,
                    response_serializer=CrisisDeck__pb2.User.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=CrisisDeck__pb2.User.FromString,
                    response_serializer=CrisisDeck__pb2.User.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=CrisisDeck__pb2.User.FromString,
                    response_serializer=CrisisDeck__pb2.User.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=CrisisDeck__pb2.UserID.FromString,
                    response_serializer=CrisisDeck__pb2.Empty.SerializeToString,
            ),
            'CreateEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEvent,
                    request_deserializer=CrisisDeck__pb2.Event.FromString,
                    response_serializer=CrisisDeck__pb2.Event.SerializeToString,
            ),
            'GetEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvent,
                    request_deserializer=CrisisDeck__pb2.EventID.FromString,
                    response_serializer=CrisisDeck__pb2.Event.SerializeToString,
            ),
            'UpdateEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEvent,
                    request_deserializer=CrisisDeck__pb2.Event.FromString,
                    response_serializer=CrisisDeck__pb2.Event.SerializeToString,
            ),
            'DeleteEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEvent,
                    request_deserializer=CrisisDeck__pb2.EventID.FromString,
                    response_serializer=CrisisDeck__pb2.Empty.SerializeToString,
            ),
            'GetEventByUser': grpc.unary_stream_rpc_method_handler(
                    servicer.GetEventByUser,
                    request_deserializer=CrisisDeck__pb2.UserID.FromString,
                    response_serializer=CrisisDeck__pb2.Event.SerializeToString,
            ),
            'CreateQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateQuery,
                    request_deserializer=CrisisDeck__pb2.Query.FromString,
                    response_serializer=CrisisDeck__pb2.Query.SerializeToString,
            ),
            'GetQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuery,
                    request_deserializer=CrisisDeck__pb2.QueryID.FromString,
                    response_serializer=CrisisDeck__pb2.Query.SerializeToString,
            ),
            'UpdateQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateQuery,
                    request_deserializer=CrisisDeck__pb2.Query.FromString,
                    response_serializer=CrisisDeck__pb2.Query.SerializeToString,
            ),
            'DeleteQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteQuery,
                    request_deserializer=CrisisDeck__pb2.QueryID.FromString,
                    response_serializer=CrisisDeck__pb2.Empty.SerializeToString,
            ),
            'CreateTweet': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTweet,
                    request_deserializer=CrisisDeck__pb2.Tweet.FromString,
                    response_serializer=CrisisDeck__pb2.Tweet.SerializeToString,
            ),
            'GetTweet': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTweet,
                    request_deserializer=CrisisDeck__pb2.TweetID.FromString,
                    response_serializer=CrisisDeck__pb2.Tweet.SerializeToString,
            ),
            'UpdateTweet': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTweet,
                    request_deserializer=CrisisDeck__pb2.Tweet.FromString,
                    response_serializer=CrisisDeck__pb2.Tweet.SerializeToString,
            ),
            'DeleteTweet': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTweet,
                    request_deserializer=CrisisDeck__pb2.TweetID.FromString,
                    response_serializer=CrisisDeck__pb2.Empty.SerializeToString,
            ),
            'SearchTweet': grpc.unary_stream_rpc_method_handler(
                    servicer.SearchTweet,
                    request_deserializer=CrisisDeck__pb2.Filters.FromString,
                    response_serializer=CrisisDeck__pb2.Tweet.SerializeToString,
            ),
            'GetTweetsByEvent': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTweetsByEvent,
                    request_deserializer=CrisisDeck__pb2.TweetID.FromString,
                    response_serializer=CrisisDeck__pb2.Tweet.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/CreateUser',
            CrisisDeck__pb2.User.SerializeToString,
            CrisisDeck__pb2.User.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/GetUser',
            CrisisDeck__pb2.User.SerializeToString,
            CrisisDeck__pb2.User.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/UpdateUser',
            CrisisDeck__pb2.User.SerializeToString,
            CrisisDeck__pb2.User.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/DeleteUser',
            CrisisDeck__pb2.UserID.SerializeToString,
            CrisisDeck__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/CreateEvent',
            CrisisDeck__pb2.Event.SerializeToString,
            CrisisDeck__pb2.Event.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/GetEvent',
            CrisisDeck__pb2.EventID.SerializeToString,
            CrisisDeck__pb2.Event.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/UpdateEvent',
            CrisisDeck__pb2.Event.SerializeToString,
            CrisisDeck__pb2.Event.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/DeleteEvent',
            CrisisDeck__pb2.EventID.SerializeToString,
            CrisisDeck__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEventByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Service/GetEventByUser',
            CrisisDeck__pb2.UserID.SerializeToString,
            CrisisDeck__pb2.Event.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/CreateQuery',
            CrisisDeck__pb2.Query.SerializeToString,
            CrisisDeck__pb2.Query.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/GetQuery',
            CrisisDeck__pb2.QueryID.SerializeToString,
            CrisisDeck__pb2.Query.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/UpdateQuery',
            CrisisDeck__pb2.Query.SerializeToString,
            CrisisDeck__pb2.Query.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/DeleteQuery',
            CrisisDeck__pb2.QueryID.SerializeToString,
            CrisisDeck__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateTweet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/CreateTweet',
            CrisisDeck__pb2.Tweet.SerializeToString,
            CrisisDeck__pb2.Tweet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTweet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/GetTweet',
            CrisisDeck__pb2.TweetID.SerializeToString,
            CrisisDeck__pb2.Tweet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTweet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/UpdateTweet',
            CrisisDeck__pb2.Tweet.SerializeToString,
            CrisisDeck__pb2.Tweet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTweet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/DeleteTweet',
            CrisisDeck__pb2.TweetID.SerializeToString,
            CrisisDeck__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchTweet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Service/SearchTweet',
            CrisisDeck__pb2.Filters.SerializeToString,
            CrisisDeck__pb2.Tweet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTweetsByEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Service/GetTweetsByEvent',
            CrisisDeck__pb2.TweetID.SerializeToString,
            CrisisDeck__pb2.Tweet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
